// <auto-generated />
using System;
using Alimentos.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alimentos.Repositorio.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Alimentos.Dominio.Cardapio", b =>
                {
                    b.Property<int>("CardapioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Lanche");

                    b.Property<decimal>("Valor");

                    b.HasKey("CardapioId");

                    b.ToTable("Cardapio");
                });

            modelBuilder.Entity("Alimentos.Dominio.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<decimal>("Valor");

                    b.HasKey("IngredienteId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Alimentos.Dominio.Lanches", b =>
                {
                    b.Property<int>("LanchesId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CardapioId");

                    b.Property<string>("Nome");

                    b.Property<decimal>("Valor");

                    b.HasKey("LanchesId");

                    b.HasIndex("CardapioId");

                    b.ToTable("Lanches");
                });

            modelBuilder.Entity("Alimentos.Dominio.Lanches", b =>
                {
                    b.HasOne("Alimentos.Dominio.Cardapio")
                        .WithMany("Lanches")
                        .HasForeignKey("CardapioId");
                });
#pragma warning restore 612, 618
        }
    }
}
